name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make all -j
    - name: test
      run: make test -j

  build-macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make all -j
    - name: test
      run: make test -j

  build-windows:

    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ilammy/msvc-dev-cmd@v1.6.0
    - name: make
      run: .\make_windows.cmd
